import { getPublicAssetUrl } from "@/lib/utils/storage";

export const objects = [
  // ═══════════════════════════════════════════════════════════════════════════
  // SUPERCARS & HYPERCARS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 1,
    name: "Porsche 911 Turbo S",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("Capture-2025-12-02-162703.png"),
    value: 311000,
  },
  {
    id: 2,
    name: "Bugatti Chiron",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("bugatti-chiron.png"),
    value: 3600000,
  },
  {
    id: 3,
    name: "Ferrari SF90 Stradale",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("ferrari-sf90.png"),
    value: 625000,
  },
  {
    id: 4,
    name: "Lamborghini Revuelto",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("lamborghini-revuelto.png"),
    value: 608000,
  },
  {
    id: 5,
    name: "McLaren P1",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("mclaren-p1.png"),
    value: 420000,
  },
  {
    id: 6,
    name: "Rolls-Royce Phantom",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("rolls-royce-phantom.png"),
    value: 400000,
  },
  {
    id: 7,
    name: "Rolls-Royce Cullinan",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("rolls-royce-cullinan.png"),
    value: 395000,
  },
  {
    id: 8,
    name: "Bentley Continental GT",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("bentley-continental.png"),
    value: 250000,
  },
  {
    id: 9,
    name: "Mercedes-Maybach S 680",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("maybach-s680.png"),
    value: 230000,
  },
  {
    id: 10,
    name: "Aston Martin DBS",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("aston-martin-dbs.png"),
    value: 330000,
  },
  {
    id: 11,
    name: "Mercedes-AMG G 63",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("amg-g63.png"),
    value: 185000,
  },
  {
    id: 12,
    name: "Koenigsegg Jesko",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("koenigsegg-jesko.png"),
    value: 3400000,
  },
  {
    id: 13,
    name: "Pagani Huayra",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("pagani-huayra.png"),
    value: 2800000,
  },
  {
    id: 14,
    name: "Ferrari 296 GTB",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("ferrari-296.png"),
    value: 350000,
  },
  {
    id: 15,
    name: "Lamborghini Huracán Sterrato",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("lamborghini-huracan.png"),
    value: 275000,
  },
  {
    id: 16,
    name: "McLaren 750S",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("mcLaren-750s.png"),
    value: 330000,
  },
  {
    id: 17,
    name: "Bentley Bentayga",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("bentley-bentayga.png"),
    value: 230000,
  },
  {
    id: 18,
    name: "Porsche Taycan Turbo S",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("porsche-taycan.png"),
    value: 200000,
  },
  {
    id: 19,
    name: "Audi R8 V10 Performance",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("audi-r8.png"),
    value: 200000,
  },
  {
    id: 20,
    name: "Mercedes-AMG SL 63",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("amg-sl63.png"),
    value: 180000,
  },
  {
    id: 21,
    name: "Maserati MC20",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("maserati-mc20.png"),
    value: 220000,
  },
  {
    id: 22,
    name: "Range Rover SV",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("range-rover-sv.png"),
    value: 250000,
  },
  {
    id: 23,
    name: "Bentley Flying Spur",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("bentley-flying-spur.png"),
    value: 250000,
  },
  {
    id: 24,
    name: "Rolls-Royce Ghost",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("rolls-royce-ghost.png"),
    value: 350000,
  },
  {
    id: 25,
    name: "Ferrari Roma",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("ferrari-roma.png"),
    value: 275000,
  },
  {
    id: 26,
    name: "Lamborghini Urus Performante",
    type: "car",
    gender: "unisex",
    image: getPublicAssetUrl("lamborghini-urus.png"),
    value: 260000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MEN'S WATCHES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 100,
    name: "Rolex Daytona",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("rolex-daytona.png"),
    value: 50000,
  },
  {
    id: 101,
    name: "Patek Philippe Nautilus",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("patek-nautilus.png"),
    value: 180000,
  },
  {
    id: 102,
    name: "Audemars Piguet Royal Oak",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("ap-royal-oak.png"),
    value: 85000,
  },
  {
    id: 103,
    name: "Richard Mille RM 011",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("richard-mille.png"),
    value: 250000,
  },
  {
    id: 104,
    name: "Rolex Submariner",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("rolex-submariner.png"),
    value: 15000,
  },
  {
    id: 105,
    name: "Omega Speedmaster Moonwatch",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("omega-speedmaster.png"),
    value: 8000,
  },
  {
    id: 106,
    name: "Vacheron Constantin Overseas",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("vacheron-overseas.png"),
    value: 30000,
  },
  {
    id: 107,
    name: "Hublot Big Bang",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("hublot-big-bang.png"),
    value: 25000,
  },
  {
    id: 108,
    name: "IWC Portugieser Chronograph",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("iwc-portugieser.png"),
    value: 12000,
  },
  {
    id: 109,
    name: "Jaeger-LeCoultre Reverso",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("jlc-reverso.png"),
    value: 15000,
  },
  {
    id: 110,
    name: "A. Lange & Söhne Lange 1",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("lange-sohne.png"),
    value: 50000,
  },
  {
    id: 111,
    name: "Breguet Classique",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("breguet-classique.png"),
    value: 25000,
  },
  {
    id: 112,
    name: "Rolex GMT-Master II",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("rolex-gmt.png"),
    value: 20000,
  },
  {
    id: 113,
    name: "Patek Philippe Calatrava",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("patek-calatrava.png"),
    value: 35000,
  },
  {
    id: 114,
    name: "Cartier Santos",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("cartier-santos.png"),
    value: 10000,
  },
  {
    id: 115,
    name: "Panerai Luminor Marina",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("panerai-luminor.png"),
    value: 12000,
  },
  {
    id: 116,
    name: "Blancpain Fifty Fathoms",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("blancpain.png"),
    value: 18000,
  },
  {
    id: 117,
    name: "TAG Heuer Monaco",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("tag-monaco.png"),
    value: 8000,
  },
  {
    id: 118,
    name: "Zenith El Primero",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("zenith-el-primero.png"),
    value: 10000,
  },
  {
    id: 119,
    name: "Rolex Day-Date 40",
    type: "watch",
    gender: "male",
    image: getPublicAssetUrl("rolex-daydate.png"),
    value: 45000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // WOMEN'S WATCHES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 150,
    name: "Cartier Panthère",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("cartier-panthere.png"),
    value: 8000,
  },
  {
    id: 151,
    name: "Chanel J12",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("chanel-j12.png"),
    value: 7500,
  },
  {
    id: 152,
    name: "Hermès H Hour",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("hermes-h-hour.png"),
    value: 4000,
  },
  {
    id: 153,
    name: "Cartier Tank Française",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("cartier-tank.png"),
    value: 6500,
  },
  {
    id: 154,
    name: "Rolex Lady-Datejust",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("rolex-lady-datejust.png"),
    value: 12000,
  },
  {
    id: 155,
    name: "Bulgari Serpenti",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("bulgari-serpenti-watch.png"),
    value: 15000,
  },
  {
    id: 156,
    name: "Chopard Happy Sport",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("chopard-happy-sport.png"),
    value: 12000,
  },
  {
    id: 157,
    name: "Piaget Possession",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("piaget-possession.png"),
    value: 10000,
  },
  {
    id: 158,
    name: "Omega Constellation",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("omega-constellation.png"),
    value: 8000,
  },
  {
    id: 159,
    name: "Van Cleef & Arpels Alhambra Watch",
    type: "watch",
    gender: "female",
    image: getPublicAssetUrl("vca-alhambra-watch.png"),
    value: 25000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // WOMEN'S HANDBAGS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 200,
    name: "Hermès Birkin 30",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("hermes-birkin.png"),
    value: 15000,
  },
  {
    id: 201,
    name: "Hermès Kelly 25",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("hermes-kelly.png"),
    value: 12000,
  },
  {
    id: 202,
    name: "Chanel Classic Flap",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("chanel-classic-flap.png"),
    value: 10800,
  },
  {
    id: 203,
    name: "Louis Vuitton Capucines",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("lv-capucines.png"),
    value: 6500,
  },
  {
    id: 204,
    name: "Dior Lady Dior",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("dior-lady-dior.png"),
    value: 6000,
  },
  {
    id: 205,
    name: "Bottega Veneta Pouch",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("bottega-pouch.png"),
    value: 3500,
  },
  {
    id: 206,
    name: "Céline Triomphe",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("celine-triomphe.png"),
    value: 4000,
  },
  {
    id: 207,
    name: "Prada Galleria",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("prada-galleria.png"),
    value: 4200,
  },
  {
    id: 208,
    name: "Fendi Baguette",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("fendi-baguette.png"),
    value: 4500,
  },
  {
    id: 209,
    name: "Goyard St. Louis",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("goyard-st-louis.png"),
    value: 2500,
  },
  // {
  //   id: 210,
  //   name: "Loewe Puzzle Bag",
  //   type: "bag",
  //   gender: "female",
  //   image:
  //     "https://bnibtqjlriohmuacvjmf.supabase.co/storage/v1/object/public/objects/loewe-puzzle.png",
  // },
  {
    id: 211,
    name: "Chanel Boy Bag",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("chanel-boy.png"),
    value: 6500,
  },
  {
    id: 212,
    name: "Gucci Jackie 1961",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("gucci-jackie.png"),
    value: 3500,
  },
  {
    id: 213,
    name: "Saint Laurent Sac de Jour",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("ysl-sac-de-jour.png"),
    value: 3500,
  },
  {
    id: 214,
    name: "Balenciaga Le City",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("balenciaga-city.png"),
    value: 2500,
  },
  {
    id: 215,
    name: "Valentino Garavani Rockstud",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("valentino-rockstud.png"),
    value: 3500,
  },
  {
    id: 216,
    name: "Givenchy Antigona",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("givenchy-antigona.png"),
    value: 2800,
  },
  {
    id: 217,
    name: "Louis Vuitton Neverfull",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("lv-neverfull.png"),
    value: 2300,
  },
  {
    id: 218,
    name: "Dior Saddle Bag",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("dior-saddle.png"),
    value: 4200,
  },
  {
    id: 219,
    name: "The Row Margaux",
    type: "bag",
    gender: "female",
    image: getPublicAssetUrl("the-row-margaux.png"),
    value: 5500,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // WOMEN'S JEWELRY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 250,
    name: "Cartier Love Ring",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("cartier-love.png"),
    value: 3000,
  },
  {
    id: 251,
    name: "Tiffany & Co. Diamond Necklace",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("tiffany-necklace.png"),
    value: 15000,
  },
  {
    id: 252,
    name: "Van Cleef & Arpels Alhambra",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("vca-alhambra.png"),
    value: 5000,
  },
  {
    id: 253,
    name: "Bulgari Serpenti Necklace",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("bulgari-serpenti.png"),
    value: 12000,
  },
  {
    id: 254,
    name: "Chopard Happy Diamonds",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("chopard-diamonds.png"),
    value: 8000,
  },
  {
    id: 255,
    name: "Harry Winston Diamond Ring",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("harry-winston.png"),
    value: 50000,
  },
  {
    id: 256,
    name: "Graff Diamond Earrings",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("graff-earrings.png"),
    value: 75000,
  },
  {
    id: 257,
    name: "Cartier Juste Un Clou",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("cartier-juste-un-clou.png"),
    value: 7500,
  },
  {
    id: 258,
    name: "Tiffany T Bracelet",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("tiffany-t.png"),
    value: 3500,
  },
  {
    id: 259,
    name: "Buccellati Cuff Bracelet",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("buccellati-cuff.png"),
    value: 15000,
  },
  {
    id: 260,
    name: "Messika Move Jewelry",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("messika-move.png"),
    value: 4000,
  },
  {
    id: 261,
    name: "Pomellato Nudo Ring",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("pomellato-nudo.png"),
    value: 5500,
  },
  {
    id: 262,
    name: "Piaget Rose Ring",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("piaget-rose.png"),
    value: 8000,
  },
  {
    id: 263,
    name: "Dior Rose des Vents",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("dior-rose-des-vents.png"),
    value: 3500,
  },
  {
    id: 264,
    name: "Chanel Coco Crush Ring",
    type: "jewelry",
    gender: "female",
    image: getPublicAssetUrl("chanel-coco-crush.png"),
    value: 4500,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRIVATE JETS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 300,
    name: "Gulfstream G700",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("gulfstream-g700.png"),
    value: 78000000,
  },
  {
    id: 301,
    name: "Bombardier Global 7500",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("bombardier-global.png"),
    value: 75000000,
  },

  {
    id: 303,
    name: "Cessna Citation X",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("cessna-citation.png"),
    value: 23000000,
  },
  {
    id: 304,
    name: "Embraer Praetor 600",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("embraer-praetor.png"),
    value: 21000000,
  },
  {
    id: 305,
    name: "Gulfstream G650ER",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("gulfstream-g650.png"),
    value: 70000000,
  },
  {
    id: 306,
    name: "Boeing Business Jet 787",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("boeing-bbj.png"),
    value: 350000000,
  },
  {
    id: 307,
    name: "Airbus ACJ320neo",
    type: "jet",
    gender: "unisex",
    image: getPublicAssetUrl("airbus-acj.png"),
    value: 115000000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YACHTS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 350,
    name: "Sunseeker Predator 92",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("sunseeker-predator.png"),
    value: 8000000,
  },
  {
    id: 351,
    name: "Azimut Grande 32M",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("azimut-grande.png"),
    value: 12000000,
  },
  {
    id: 352,
    name: "Princess Y85",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("princess-y85.png"),
    value: 7000000,
  },
  {
    id: 353,
    name: "Riva 110 Dolcevita",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("riva-dolcevita.png"),
    value: 15000000,
  },
  {
    id: 354,
    name: "Benetti Oasis 40M",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("benetti-oasis.png"),
    value: 25000000,
  },
  {
    id: 355,
    name: "Ferretti 1000",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("ferretti-1000.png"),
    value: 10000000,
  },
  {
    id: 356,
    name: "Lürssen Superyacht",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("lurssen.png"),
    value: 150000000,
  },
  {
    id: 357,
    name: "Feadship Superyacht",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("feadship.png"),
    value: 80000000,
  },
  {
    id: 358,
    name: "Pershing 140",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("pershing-140.png"),
    value: 35000000,
  },
  {
    id: 359,
    name: "Sanlorenzo SX112",
    type: "yacht",
    gender: "unisex",
    image: getPublicAssetUrl("sanlorenzo.png"),
    value: 15000000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PREMIUM SPIRITS & CHAMPAGNE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 400,
    name: "Dom Pérignon Vintage",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("dom-perignon.png"),
    value: 250,
  },
  {
    id: 401,
    name: "Louis XIII Cognac",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("louis-xiii.png"),
    value: 4500,
  },
  {
    id: 402,
    name: "Clase Azul Ultra",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("clase-azul.png"),
    value: 2000,
  },
  {
    id: 403,
    name: "The Macallan 25 Year",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("macallan-25.png"),
    value: 3500,
  },
  {
    id: 404,
    name: "Cristal Champagne",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("cristal.png"),
    value: 300,
  },
  {
    id: 405,
    name: "Krug Grande Cuvée",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("krug.png"),
    value: 280,
  },
  {
    id: 406,
    name: "Hennessy Paradis",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("hennessy-paradis.png"),
    value: 1200,
  },
  {
    id: 407,
    name: "Johnnie Walker Blue Label",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("johnnie-walker-blue.png"),
    value: 250,
  },
  {
    id: 408,
    name: "Yamazaki 18 Year",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("yamazaki-18.png"),
    value: 600,
  },
  {
    id: 409,
    name: "Pappy Van Winkle 23 Year",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("pappy-van-winkle.png"),
    value: 3000,
  },
  {
    id: 410,
    name: "Armand de Brignac Ace of Spades",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("ace-of-spades.png"),
    value: 350,
  },
  {
    id: 411,
    name: "Perrier-Jouët Belle Epoque",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("perrier-jouet.png"),
    value: 250,
  },
  {
    id: 412,
    name: "Hibiki 21 Year",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("hibiki-21.png"),
    value: 900,
  },
  {
    id: 413,
    name: "Dalmore 25 Year",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("dalmore-25.png"),
    value: 2000,
  },
  {
    id: 414,
    name: "Château Margaux",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("chateau-margaux.png"),
    value: 700,
  },
  {
    id: 415,
    name: "Opus One",
    type: "beverage",
    gender: "unisex",
    image: getPublicAssetUrl("opus-one.png"),
    value: 500,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DESIGNER FASHION - WOMEN
  // ═══════════════════════════════════════════════════════════════════════════
  // {
  //   id: 500,
  //   name: "Fendi Fur Coat",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/fendi-coat.png",
  // },
  // {
  //   id: 501,
  //   name: "Valentino Couture Gown",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/valentino-gown.png",
  // },
  // {
  //   id: 502,
  //   name: "Chanel Tweed Jacket",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/chanel-tweed.png",
  // },
  // {
  //   id: 503,
  //   name: "Oscar de la Renta Evening Dress",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/oscar-de-la-renta.png",
  // },
  // {
  //   id: 504,
  //   name: "Christian Louboutin So Kate",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/louboutin-so-kate.png",
  // },
  // {
  //   id: 505,
  //   name: "Manolo Blahnik Hangisi",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/manolo-hangisi.png",
  // },
  // {
  //   id: 506,
  //   name: "Jimmy Choo Bing",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/jimmy-choo-bing.png",
  // },
  // {
  //   id: 507,
  //   name: "Hermès Silk Scarf",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/hermes-scarf.png",
  // },
  // {
  //   id: 508,
  //   name: "Dior Bar Jacket",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/dior-bar-jacket.png",
  // },
  // {
  //   id: 509,
  //   name: "Loro Piana Cashmere Cape",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/loro-piana-cape.png",
  // },
  // {
  //   id: 510,
  //   name: "Max Mara Teddy Coat",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/max-mara-teddy.png",
  // },
  // {
  //   id: 511,
  //   name: "Bottega Veneta Dress",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/bottega-dress.png",
  // },
  // {
  //   id: 512,
  //   name: "Alexander McQueen Gown",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/mcqueen-gown.png",
  // },
  // {
  //   id: 513,
  //   name: "Versace Medusa Dress",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/versace-dress.png",
  // },
  // {
  //   id: 514,
  //   name: "Gucci Flora Dress",
  //   type: "fashion",
  //   gender: "female",
  //   image: "/images/objects/gucci-flora.png",
  // },

  // ═══════════════════════════════════════════════════════════════════════════
  // DESIGNER FASHION - MEN
  // ═══════════════════════════════════════════════════════════════════════════
  // {
  //   id: 550,
  //   name: "Tom Ford Tuxedo",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/tom-ford-tuxedo.png",
  // },
  // {
  //   id: 551,
  //   name: "Ermenegildo Zegna Suit",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/zegna-suit.png",
  // },
  // {
  //   id: 552,
  //   name: "Brunello Cucinelli Cashmere Sweater",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/cucinelli-sweater.png",
  // },
  // {
  //   id: 553,
  //   name: "Loro Piana Cashmere Coat",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/loro-piana-coat.png",
  // },
  // {
  //   id: 554,
  //   name: "Brioni Suit",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/brioni-suit.png",
  // },
  // {
  //   id: 555,
  //   name: "Kiton Bespoke Suit",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/kiton-suit.png",
  // },
  // {
  //   id: 556,
  //   name: "Berluti Leather Jacket",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/berluti-jacket.png",
  // },
  // {
  //   id: 557,
  //   name: "John Lobb Oxford Shoes",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/john-lobb.png",
  // },
  // {
  //   id: 558,
  //   name: "Salvatore Ferragamo Loafers",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/ferragamo-loafers.png",
  // },
  // {
  //   id: 559,
  //   name: "Hermès Tie",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/hermes-tie.png",
  // },
  // {
  //   id: 560,
  //   name: "Canali Sport Coat",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/canali-coat.png",
  // },
  // {
  //   id: 561,
  //   name: "Louis Vuitton Leather Jacket",
  //   type: "fashion",
  //   gender: "male",
  //   image: "/images/objects/lv-leather-jacket.png",
  // },

  // ═══════════════════════════════════════════════════════════════════════════
  // LUXURY ACCESSORIES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 600,
    name: "Saint Laurent Sunglasses",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("ysl-sunglasses.png"),
    value: 500,
  },
  {
    id: 601,
    name: "Rimowa Classic Cabin",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("rimowa.png"),
    value: 1400,
  },
  {
    id: 602,
    name: "Louis Vuitton Horizon Trunk",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("lv-trunk.png"),
    value: 9000,
  },
  {
    id: 603,
    name: "Montblanc Meisterstück Pen",
    type: "accessory",
    gender: "male",
    image: getPublicAssetUrl("montblanc-pen.png"),
    value: 800,
  },
  {
    id: 604,
    name: "S.T. Dupont Lighter",
    type: "accessory",
    gender: "male",
    image: getPublicAssetUrl("dupont-lighter.png"),
    value: 1200,
  },
  {
    id: 605,
    name: "Tom Ford Sunglasses",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("tom-ford-sunglasses.png"),
    value: 500,
  },
  {
    id: 606,
    name: "Hermès Belt",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("hermes-belt.png"),
    value: 1000,
  },
  {
    id: 607,
    name: "Goyard Passport Holder",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("goyard-passport.png"),
    value: 800,
  },
  {
    id: 608,
    name: "Cartier Lighter",
    type: "accessory",
    gender: "male",
    image: getPublicAssetUrl("cartier-lighter.png"),
    value: 2500,
  },
  {
    id: 609,
    name: "Globe-Trotter Luggage",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("globe-trotter.png"),
    value: 2500,
  },
  {
    id: 610,
    name: "Persol Sunglasses",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("persol.png"),
    value: 400,
  },
  {
    id: 611,
    name: "Gucci Horsebit Belt",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("gucci-belt.png"),
    value: 600,
  },
  {
    id: 612,
    name: "Dita Sunglasses",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("dita-sunglasses.png"),
    value: 700,
  },
  {
    id: 613,
    name: "Bottega Veneta Wallet",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("bottega-wallet.png"),
    value: 700,
  },
  {
    id: 614,
    name: "Louis Vuitton Card Holder",
    type: "accessory",
    gender: "unisex",
    image: getPublicAssetUrl("lv-cardholder.png"),
    value: 400,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOTORCYCLES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 750,
    name: "Ducati Panigale V4",
    type: "motorcycle",
    gender: "unisex",
    image: getPublicAssetUrl("ducati-panigale.png"),
    value: 40000,
  },
  {
    id: 751,
    name: "BMW R 18",
    type: "motorcycle",
    gender: "unisex",
    image: getPublicAssetUrl("bmw-r18.png"),
    value: 22000,
  },
  {
    id: 752,
    name: "Harley-Davidson CVO",
    type: "motorcycle",
    gender: "unisex",
    image: getPublicAssetUrl("harley-cvo.png"),
    value: 50000,
  },
  {
    id: 753,
    name: "MV Agusta Superveloce",
    type: "motorcycle",
    gender: "unisex",
    image: getPublicAssetUrl("mv-agusta.png"),
    value: 35000,
  },
  {
    id: 754,
    name: "Triumph Rocket 3",
    type: "motorcycle",
    gender: "unisex",
    image: getPublicAssetUrl("triumph-rocket.png"),
    value: 28000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXOTIC EXPERIENCES / PROPS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 850,
    name: "Stacks of Cash",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("cash-stacks.png"),
    value: 1000000,
  },
  {
    id: 851,
    name: "Gold Bars",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("gold-bars.png"),
    value: 500000,
  },

  {
    id: 853,
    name: "Fine Art Painting",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("fine-art.png"),
    value: 1000000,
  },
  {
    id: 854,
    name: "Crystal Chandelier",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("chandelier.png"),
    value: 100000,
  },
  {
    id: 855,
    name: "Black Amex Card",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("black-amex.png"),
    value: 10000,
  },
  {
    id: 856,
    name: "Exotic Pet (Tiger Cub)",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("tiger-cub.png"),
    value: 25000,
  },
  {
    id: 857,
    name: "Goat",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("goat.png"),
    value: 10000,
  },
  {
    id: 858,
    name: "Private Helicopter",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("helicopter.png"),
    value: 5000000,
  },
  {
    id: 860,
    name: "Poker Chips & Cards",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("poker-chips.png"),
    value: 50000,
  },
  {
    id: 861,
    name: "Caviar & Champagne",
    type: "prop",
    gender: "unisex",
    image: getPublicAssetUrl("caviar-champagne.png"),
    value: 5000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MEN'S ACCESSORIES & JEWELRY
  // ═══════════════════════════════════════════════════════════════════════════
];

// Helper functions to filter objects
export const getObjectsByType = (type: string) =>
  objects.filter((obj) => obj.type === type);

export const getObjectsByGender = (gender: string) =>
  objects.filter((obj) => obj.gender === gender || obj.gender === "unisex");

export const getObjectTypes = () => [
  ...new Set(objects.map((obj) => obj.type)),
];

export const objectTypeLabels: Record<string, string> = {
  car: "Supercars",
  watch: "Watches",
  bag: "Handbags",
  jewelry: "Jewelry",
  jet: "Private Jets",
  yacht: "Yachts",
  beverage: "Premium Spirits",
  fragrance: "Fragrances",
  fashion: "Designer Fashion",
  accessory: "Accessories",
  cigar: "Premium Cigars",
  motorcycle: "Motorcycles",
  prop: "Props & Experiences",
};
